name: PR Deploy and Audit
on: [pull_request]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # - name: Vercel Action
            #   id: vercel_action
            #   uses: amondnet/vercel-action@v20
            #   with:
            #       vercel-token: ${{ secrets.VERCEL_TOKEN }}
            #       github-token: ${{ secrets.GITHUB_TOKEN }}
            #       vercel-org-id: ${{ secrets.ORG_ID}}
            #       vercel-project-id: ${{ secrets.PROJECT_ID}}
            - name: Audit URLs using Lighthouse
              id: lighthouse_audit
              uses: treosh/lighthouse-ci-action@v7
              with:
                  urls: |
                      https://www.sitepen.com/
                      https://www.sitepen.com/blog/
                  budgetPath: '.github/lighthouse/budget.json'
                  uploadArtifacts: true
                  temporaryPublicStorage: true
                  runs: 3
            #   env:
            #       LHCI_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - name: Format success lighthouse score
              id: success_lighthouse_score
              if: ${{ always() }}
              uses: actions/github-script@v4
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      const links = ${{ steps.lighthouse_audit.outputs.links }}
                      const results = (${{ steps.lighthouse_audit.outputs.manifest }}).filter(result => result.isRepresentativeRun);

                      const formatResult = (res) => Math.round((res * 100));
                      const score = res => res >= 90 ? '🟢' : res >= 50 ? '🟠' : '🔴';

                      const comment = results.map((result) => {
                        const summary = result.summary;
                        const url = result.url;

                        return `⚡️ [Lighthouse report](${links[url]}) for the changes in this PR:

                          | Category | Score |
                          | --- | --- |
                          | ${score(summary.performance)} Performance | ${summary.performance} |
                          | ${score(summary.accessibility)} Accessibility | ${summary.accessibility} |
                          | ${score(summary['best-practices'])} Best practices | ${summary['best-practices']} |
                          | ${score(summary.seo)} SEO | ${summary.seo} |
                          | ${score(summary.pwa)} PWA | ${summary.pwa} |

                          *Lighthouse ran on [${url}](${url})*
                        `;
                      }).join('\n\n');

                      core.setOutput("comment", comment);
            - name: Format Error lighthouse score
              id: cancelled_lighthouse_score
              if: ${{ cancelled() }}
              uses: actions/github-script@v4
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      console.log('CANCELLED');
                      console.log(${{ steps.lighthouse_audit.outputs.assertionResults }})
            - name: Add comment to PR
              id: comment_to_pr
              if: ${{ always() }}
              uses: marocchino/sticky-pull-request-comment@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ github.event.pull_request.number }}
                  header: lighthouse
                  message: |
                      ${{ steps.success_lighthouse_score.outputs.comment }}
                  #   ${{ steps.vercel_action.outputs.preview-url }}
